version: '{build}'

clone_depth: 50

environment:
  matrix:
    - platform: x86
      JAVA_HOME: ${ProgramFiles(x86)}\Java\jdk1.6.0
      MVN_VERSION: 3.2.5
      M2_HOME: $(SystemDrive)\bin\apache-maven-$(MVN_VERSION)
    - platform: x86
      JAVA_HOME: ${ProgramFiles(x86)}\Java\jdk1.7.0
      MVN_VERSION: 3.5.2
    - platform: x86
      JAVA_HOME: ${ProgramFiles(x86)}\Java\jdk1.8.0
      MVN_VERSION: 3.5.2
    - platform: x64
      JAVA_HOME: $(ProgramFiles)\Java\jdk1.6.0
      MVN_VERSION: 3.2.5
      M2_HOME: $(SystemDrive)\bin\apache-maven-$(MVN_VERSION)
    - platform: x64
      JAVA_HOME: $(ProgramFiles)\Java\jdk1.7.0
      MVN_VERSION: 3.5.2
    - platform: x64
      JAVA_HOME: $(ProgramFiles)\Java\jdk1.8.0
      MVN_VERSION: 3.5.2
      ARTIFACTS_PATH: target\*.jar
      VT_API_URL: https://www.virustotal.com/vtapi/v2/file/scan
      VT_API_DELAY: 15
      VT_API_KEY:
        secure: 3sqJDjLAS708tR/LiAqKLZTnLLrhGJuWVzzI4nCjLbUUsZB+PPRG3y0BWWnMo14CDhBT4v6yjHTA23RdopoHDWJlBcGhKELKZOLhHsnJLU8=
      GITHUB_SITE_MAVEN_PLUGIN_TOKEN:
        secure: iZF8b6d29Wk2VAubvw8tEwOMt0kB0Krq2e0Ie0Up15EfEfEBnvgs05/LbjhIODWi

cache:
  - $(ChocolateyInstall)\lib -> .appveyor.yml
  - $(ChocolateyInstall)\bin -> .appveyor.yml
  - $(SystemDrive)\bin -> .appveyor.yml

install:
  - ps: cinst maven -i --version $env:MVN_VERSION --allow-empty-checksums
  - cmd: PATH %SystemDrive%\bin\apache-maven-%MVN_VERSION%\bin;%ChocolateyInstall%\lib\maven\apache-maven-%MVN_VERSION%\bin;%JAVA_HOME%\bin;%PATH%

before_build:
  - java -Xmx32m -version
  - javac -J-Xmx32m -version
  - mvn -version

build_script:
  - mvn clean install

after_build:
  - cmd: IF DEFINED GITHUB_SITE_MAVEN_PLUGIN_TOKEN mvn deploy -DskipTests
  - cmd: IF "%APPVEYOR_REPO_TAG%" == "true" IF DEFINED VT_API_KEY FOR /R target %%i IN (*.jar) DO ECHO %%i & curl -v -F "file=@%%i" -F apikey=%VT_API_KEY% %VT_API_URL% & TIMEOUT %VT_API_DELAY% /NOBREAK

artifacts:
  - path: $(ARTIFACTS_PATH)
    type: file

deploy:
  description: 'Autogenerated'
  provider: GitHub
  auth_token:
    secure: iZF8b6d29Wk2VAubvw8tEwOMt0kB0Krq2e0Ie0Up15EfEfEBnvgs05/LbjhIODWi
  draft: true
  on:
    appveyor_repo_tag: true
