environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.6.0
      JRE6_HOME=C:\Program Files\Java\jdk1.6.0\jre

    - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
      JRE6_HOME=C:\Program Files\Java\jdk1.6.0\jre

    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
      JRE6_HOME=C:\Program Files\Java\jdk1.6.0\jre

install:
  - ps: if(!(Test-Path -Path 'C:\ProgramData\chocolatey\lib\ant\apache-ant-1.9.8\' )){ cinst ant -i -Version 1.9.8 }
  - cmd: SET PATH=C:\ProgramData\chocolatey\lib\ant\apache-ant-1.9.8\bin;%JAVA_HOME%\bin;%PATH%

cache:
  - C:\ProgramData\chocolatey\lib\ant\apache-ant-1.9.8

platform:
  - x86
  - x64

build_script:
  - ant all
