environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.6.0
    - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - ps: if(!(Test-Path -Path 'C:\ProgramData\chocolatey\lib\ant\apache-ant-1.9.8\' )){ cinst ant -i -Version 1.9.8 }
  - cmd: SET PATH=C:\ProgramData\chocolatey\lib\ant\apache-ant-1.9.8\bin;%JAVA_HOME%\bin;%PATH%

cache:
  - C:\ProgramData\chocolatey\lib\ant\apache-ant-1.9.8

platform:
  - x86
  - x64

#configuration:
#  - Release

build_script:
  - ant all

#test_script:
#- echo "Nothing."
