language: java
script: ant all
env: JRE6_HOME=/usr/lib/jvm/java-6-openjdk-amd64/jre
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6
sudo: required
before_script:
  - sudo apt-get -qq update 
  - sudo apt-get -y --force-yes install ant
