language: java

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: linux
      jdk: openjdk7
    - os: osx

addons:
  sonarcloud:
    organization: "albertus82-github"

env:
  global:
    - secure: "Kf/FmAkFyIGcGhXuI6ByfRUg3Uhyj/Dr2+3Bc4croxLIQ/xYMEepN21+OBer0l2ERJNlJaK6GrBTkFArPQ7mhnqwiNcBNR0+B96UxWGcr+mrtW2BjVsaiafaEJByw44i+JV3Wy/EbGQZ8N3cW09C2vU75s6klS92lC2AYOFXrrBgoZBtrLB470z7lLK+RyvSbcDQDqdPhGI518O0XbH7Fv/QEk61yUlg+TgnJmPbLxXqpmMpQu2Toot25FjENpq8w2+zuF3CEmvq+0qmscyzuWytRkF06NbatPGnlVASyAuHQ+VwO8NzgBV44/Ja1TuUwE4Hvy73FBiy0VKStkgBbWomv0KmrqoV8tABLJjIbztm2qn/k131oCpiSuR73usMeg3G9/cRxKBT1gsbVjWpgbHwgCIytYlo7oHv7fsThutuBCMMqfczyPh8WEHY6SHxc/68rktQc6cRHhtap5yr9+7Nm9KAOiInIwYJ18V+J0ZwnzhAJJ8CxweFWZIK4dK//8kV7RqE3tlqOjnNDlBmWxbzU0ykG19VaeRnuGQtVRu+lthOBs+tIjfm8NCg+qe7VJgqdV1N1BqDZyE+/CMocTR+kn9FRaI3D5TDJxgyB4BKgV7i//anJm+142GQkq2Ly1qe3YecNtuHWngEEUyEwaXs036dN7DJ9vDRkU8M0cg="
    - secure: "QbrAaCSM5ToNJBFXFQG6+T9BzOcWVbqfxyr19K6sZY1g/x+TW4YCjon30A4qYE5rH2BvpQL79tVx6D+C8U3IBCJazUlM1W0BDAtckxOlJmmGxTzDOOFbR+tQqolSy6KaFnYV4Q3rH3Wn9KhBEeoDZjYMXf3A1otnqWOQX3CncejdgXSKXX2LxQ11pFOVpbCo4g7k+5NFv99DDOnIoNO9BTwdhTSmkkKVTVhYFJJAFR42rpzYw6qI2q2qZi/WxIUL9ZmkePiz95kSS9ZFLpTv9/lW9do68bJshsQIhgCNS+dLI0HvEfaRAYFbx0X0S+Qz83iGji2YPvVJmWLGASHPCdcwegAUh+Fo3NBM5PUOCUEAH87pJ3VxmyY+kRGZV6xs+TdwOYdy+tGM/uyGODLeGM2vU1zSyUqLifrdUbNP3nInqeD9Myiqt2GjQQTIpS8kwu6GD2t0EUzy1QHwYetbL1WdGNwPlqhswXGXVr6eQ3PqbBnitHeBeWmwIId6fZxl7Xq0GZ0Gv8K8FmKku5VfaV1Esww2qAMBhRp2TkxNcaca/ojQYyvZtttFHbT8CgxJWqO01kltEvEHaweZvPY6Uss6sjn3Jv3mKMbv1g2L33H47k1Z5v5iLo51yiiDrgdLCImjzEAS0m0itJGVkd824+aWkJxzTJptQo6B697bzLs="

script:
  - if [ "$TRAVIS_JDK_VERSION" == "oraclejdk8" ]; then mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent deploy sonar:sonar; else mvn deploy; fi;


after_success: |
  if [ "$TRAVIS_JDK_VERSION" == "oraclejdk8" ]; then
    cd mvn-repo
    git init
    git checkout -b gh-maven
    git add .
    git -c user.name='travis' -c user.email='travis' commit -m init
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    tree -D
    #git push -f -q https://Albertus82:$GITHUB_TOKEN@github.com/Albertus82/JFaceUtils gh-maven &2>/dev/null
    cd ..
  fi
