language: java
script: ant jars
env: JAVA_HOME_BOOTCLASSPATH=/usr/lib/jvm/java-6-openjdk-amd64
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6
before_install:
  - wget wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/7u79-b15/jdk-7u79-linux-x64.tar.gz
  - tar -xf jdk-7u79-linux-x64.tar.gz