language: java
script: ant jars
env: JAVA_HOME_BOOTCLASSPATH=/usr/lib/jvm/java-6-openjdk-amd64
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6
addons:
  apt:
    packages:
      - oracle-java8-installer
