name: build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        java: [ '7', '8', '9', '10', '11' ]
        os: [ 'windows-latest', 'ubuntu-latest', 'macOS-latest' ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-java@master
      with:
        java-version: ${{ matrix.java }}
    - run: mvn clean verify -B -V
