name: Java CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        java: [ '6', '7', '8' ]
        platform: [ 'windows-latest', 'ubuntu-latest' ]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build with Maven
      run: mvn clean verify
