name: build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        java: [ '7', '8', '9', '10', '11' ]
        platform: [ 'windows-latest', 'ubuntu-latest', 'macOS-latest' ]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - run: mvn clean verify -V
    - if: matrix.java == '11' && matrix.platform == 'ubuntu-latest'
      run: mvn org.sonarsource.scanner.maven:sonar -Dsonar.organization=albertus82-github
