name: build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        java: [ '7', '8', '9', '10', '11' ]
        os: [ 'windows-latest', 'ubuntu-latest', 'macOS-latest' ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - run: mvn clean verify -V
    - if: os == 'ubuntu-latest' && java == '11'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn deploy -Dregistry=https://maven.pkg.github.com/albertus82 -Dtoken=GITHUB_TOKEN
